const api = process.env.NEXT_PUBLIC_API_URL;
export const GET_USER_ROUTE = api + "/profile/info";
export const GET_USER_HOME = api + "/home/menu_types?username=";
export const GET_COFFEE_MENU = api + "/home/menu_types";
export const GET_LOGIN_ROUTE = api + "/auth/login";
export const GET_LOGOUT_ROUTE = api + "/auth/logout";
export const GET_FOODS = api + "/foods";
export const GET_RATING = api + "/ratings?username=";
export const CREATE_ITEM = api + "/foods";
export const CREATE_REVIEW = api + "/ratings?username=";
export const DELETE_ITEM = api + "/foods";
export const DELETE_CATEGORY = api + "/categories";
export const GET_CATEGORIES = api + "/categories";
export const CREATE_CATEGORIES = api + "/categories";
export const GET_EDIT_ITEM = api + "/foods";
export const GET_EDIT_CATEGORY = api + "/categories";
export const GET_REPORTS = api + "/reports/views";
